server:
  compression:
    enabled: true #是否开启压缩，默认为 false
    min-response-size: 1 #执行压缩的阈值，默认为 2048

easyjava:
  # 当前系统名称
  name: EasyJavaSE
  # 当前系统版本
  version: 1.1.1
  # 版权年份
  copyrightYear: 2024
  # 作者邮箱
  email: 1134135987@qq.com
  # 作者QQ
  qq: 1134135987
  # 本系统的开发作者
  author: bobo
  # 新用户注册时的默认头像地址
  userDefaultAvatarPath: https://img2.baidu.com/it/u=1016407180,2828407920&fm=253&fmt=auto&app=138&f=JPEG?w=800&h=800
  outTime: 2024-10-01T23:59:59.902300+08:00 # CommonTask
  key: d8bda68af0902387c8a9070a846c9d2a # 调用聚合数据官网接口获取新闻的key(在个人中心->我的数据,接口名称上方查看)
  ak: 32YhnFxMHceHvYClZrukNOZzWxsmDqdX # 调用百度API获取天气情况
  sk: eV3k3dYx66QFfmUvZx4H58bSWil4TnHv # 调用百度API获取天气情况

# actable的配置信息
mybatis:
  table:
    auto: none
    #create	系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
    #update	系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
    #none 		系统不做任何处理。
    #add		新增表/新增字段/新增索引/新增唯一约束的功能，不做做修改和删除 (只在版本1.0.9.RELEASE及以上支持)。
  model:
    pack: cn.wujiangbo.domain.system #扫描用于创建表的对象的包名，多个包用“,”隔开
  database:
    type: mysql #数据库类型，目前只支持mysql

#MyBatis-Plus相关配置
mybatis-plus:
  global-config:
    #是否开启 LOGO(控制台是否打印MybatisPlus的logo)
    banner: true
  #指定Mapper.xml路径，如果与Mapper路径相同的话，可省略
  mapper-locations: classpath*:cn/wujiangbo/mapper/*/*Mapper.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰大小写自动转换
    call-setters-on-nulls: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启控制台sql输出
    cache-enabled: false #是否开启缓存
  type-aliases-package: cn.wujiangbo.domain

spring:
  profiles:
    active: dev #本地开发环境
#    active: prod #线上生产环境
  application:
    name: EasyJavaSE #服务名
  main:
    #允许重复的 bean 被覆盖
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 30MB #配置单个文件最大上传大小
      max-request-size: 100MB #配置单个请求最大上传大小(一次请求可以上传多个文件)

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

#OSS相关配置
file:
  alicloud:
    enable: true  #是否开启OSS上传
    bucket-name: news20244 #上传空间bucket
    access-key: LTAI5tKfERVozHAdU84ugJvZ #你的key
    secret-key: t7BeMGLw326HSGr41Tykv6vwBz9zKx #你的秘钥
    endpoint: oss-cn-beijing.aliyuncs.com  #上传端点

#yml加密配置
jasypt:
  encryptor:
    password: easyjava#KLOp*AndSe
    algorithm: PBEWithMD5AndDES